# Generated by Django 3.0.5 on 2020-04-20 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Mensajes de Contacto',
                'verbose_name_plural': 'Mensajes de contacto',
            },
        ),
    ]
