# Generated by Django 3.0.5 on 2020-04-07 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20200404_0155'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Tipo de propiedad')),
            ],
            options={
                'verbose_name': 'Tipo de Propiedad',
                'verbose_name_plural': 'Tipos de Propiedad',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='Comentario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
            },
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripcion de la propiedad')),
                ('direction', models.CharField(max_length=1000, verbose_name='Direccion')),
                ('requirements', models.TextField(verbose_name='Requisitos de alquiler')),
                ('city', models.CharField(max_length=200, verbose_name='Ciudad')),
                ('rent_price', models.FloatField(verbose_name='Precio de renta')),
                ('property_state', models.BooleanField(verbose_name='Rentado / No Rentado')),
                ('publication_date', models.DateField(auto_now=True, verbose_name='Fecha de publicación')),
                ('comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment.Comments', verbose_name='Comentarios')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile', verbose_name='Dueño')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment.ApartmentType', verbose_name='Tipo de propiedad')),
            ],
            options={
                'verbose_name': 'Propiedad',
                'verbose_name_plural': 'Propiedades',
            },
        ),
    ]
