# Generated by Django 3.0.5 on 2020-05-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmenttype',
            name='name',
            field=models.CharField(choices=[('CA', 'Casa'), ('AP', 'Apartamento'), ('PI', 'Piso'), ('PL', 'Planta'), ('HB', 'Habitacion')], max_length=100, verbose_name='Tipo de propiedad'),
        ),
    ]
