# Generated by Django 3.0.5 on 2020-05-10 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0003_auto_20200510_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='comments',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='apartment.Comments', verbose_name='Comentarios'),
        ),
    ]
