# Generated by Django 3.0.5 on 2020-05-12 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0006_comments_comment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='comments',
        ),
        migrations.AddField(
            model_name='comments',
            name='apartment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='apartment.Apartment'),
        ),
    ]
