# Generated by Django 3.0.5 on 2020-04-13 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
